name: Official Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r "scripts/publish/requirements.txt"
      - name: build package
        run: |
          rm -rf dist
          mkdir -p dist
          python -m build
      - name: release
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
